CREATE TABLE IF NOT EXISTS "public"."notices" (
  "id" bigint NOT NULL,
  "slug" "text" NOT NULL,
  "category" "text" NOT NULL,
  "title" "text" NOT NULL,
  "subtitle" "text" NOT NULL,
  "content" "text" NOT NULL,
  "cover_image_url" "text" NOT NULL,
  "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE "public"."notices" OWNER TO "postgres";
ALTER TABLE "public"."notices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
  SEQUENCE NAME "public"."notices_id_seq"
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1
);

ALTER TABLE ONLY "public"."notices"
  ADD CONSTRAINT "notices_pkey" PRIMARY KEY ("id");

ALTER TABLE "public"."notices" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."notices" TO "anon";
GRANT ALL ON TABLE "public"."notices" TO "authenticated";
GRANT ALL ON TABLE "public"."notices" TO "service_role";

CREATE POLICY "Allow read access for all users" ON "public"."notices" FOR SELECT USING (true);
